services:
  phoenix:
    image: arizephoenix/phoenix:latest
    pull_policy: always
    ports:
      - "6006:6006"
  backend:
    build: backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COLLECTOR_ENDPOINT=http://phoenix:6006/v1/traces
      - PHOENIX_API_ENDPOINT=http://phoenix:6006
      - PROD_CORS_ORIGIN=http://localhost:3000
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000"]
      interval: 5s
      timeout: 1s
      retries: 5
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
