[tool.poetry]
name = "dspy-rag-frontend"
version = "0.1.0"
description = "Streamlit frontend for DSPy"
authors = ["diicell"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
streamlit = "^1.32.0"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
