[tool.poetry]
name = "dspy-rag-fastapi"
version = "0.2.0"
description = "FastAPI wrapper around dspy"
authors = ["diicell", "mikeldking"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.27.1"}
arize-phoenix = "^3.4.1"
openinference-instrumentation-dspy = "^0.1.4"
opentelemetry-exporter-otlp = "^1.23.0"
weaviate-client = "^4.5.6"
structlog = "^24.1.0"
openai = "^1.23.5"
tokenizers = "^0.19.1"
openinference-semantic-conventions = "^0.1.5"
dspy = {git = "https://github.com/stanfordnlp/dspy.git"}
cohere = "^5.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
