[tool.poetry]
name = "dspy-rag-fastapi"
version = "0.2.0"
description = "FastAPI wrapper around dspy"
authors = ["diicell", "mikeldking"]
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
fastapi = ">=0.118.0"
uvicorn = {extras = ["standard"], version = "^0.34.0"}
arize-phoenix = ">=11.21.0"
openinference-instrumentation-dspy = "^0.1.19"
opentelemetry-exporter-otlp = "^1.31.1"
weaviate-client = "^4.11.3"
structlog = "^25.2.0"
openai = "^1.68.2"
tokenizers = "^0.21.1"
openinference-semantic-conventions = "^0.1.15"
dspy-ai = "^2.6.15"
cohere = "^5.14.0"
h11 = ">0.14.0"
protobuf = ">=5.29.5"
setuptools = ">=78.1.1"
starlette = ">=0.49.1"
urllib3 = ">=2.6.0"
requests = ">=2.32.4"
aiohttp = ">=3.13.3"
authlib = ">=1.6.6"
python-multipart = ">=0.0.22"
filelock = "3.20.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
