[tool]
[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = [ "Marcus Schiesser <mail@marcusschiesser.de>" ]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11,<3.12"
fastapi = ">=0.118.0"
python-dotenv = "^1.0.0"
llama-index = "^0.13.0"
llama-index-core = "^0.13.0"
openinference-semantic-conventions = "*"
openinference-instrumentation-llama-index = "^4.3.0"
opentelemetry-exporter-otlp = "^1.25.0"
h11 = ">0.14.0"
starlette = ">=0.49.1"
aiohttp = ">=3.13.3"
pypdf = ">=6.6.2"
protobuf = ">=6.33.5"
urllib3 = ">=2.6.3"
requests = ">=2.32.4"

[tool.poetry.dependencies.uvicorn]
extras = [ "standard" ]
version = "^0.23.2"

[tool.poetry.dependencies.docx2txt]
version = "^0.8"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
